"""create shortlists table

Revision ID: fc05fcc86e27
Revises: 002
Create Date: 2026-08-21 18:06:16.367794
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc05fcc86e27"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shortlists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("role_title", sa.String(), nullable=True),
        sa.Column("total_applicants", sa.Integer(), nullable=False),
        sa.Column("shortlist_size", sa.Integer(), nullable=False),
        sa.Column(
            "candidates",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shortlists_id"), "shortlists", ["id"], unique=False)
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_shortlists_id"), table_name="shortlists")
    op.drop_table("shortlists")
    # ### end Alembic commands ###
