"""
Shortlist model for HireFlow AI.

Stores hiring shortlists generated by scoring applicants against a JD.
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    DateTime,
    Integer,
    String,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import JSON, Uuid

from src.config.database import Base

# JSONB on PostgreSQL, falls back to JSON on SQLite (for tests).
JSONBCompat = JSONB().with_variant(JSON, "sqlite")


class Shortlist(Base):
    """Represents a generated hiring shortlist.

    Attributes:
        id: Unique identifier (UUID).
        company_name: Name of the hiring company (optional).
        role_title: Job title from the JD (optional).
        total_applicants: The total number of applicants considered.
        shortlist_size: The number of candidates requested for the shortlist.
        candidates: JSONB array of shortlisted candidates with scores, gaps, and summaries.
        created_at: Record creation timestamp.
    """

    __tablename__ = "shortlists"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, default=uuid.uuid4, index=True
    )
    company_name: Mapped[str | None] = mapped_column(String, nullable=True)
    role_title: Mapped[str | None] = mapped_column(String, nullable=True)
    total_applicants: Mapped[int] = mapped_column(Integer, default=0)
    shortlist_size: Mapped[int] = mapped_column(Integer, default=0)
    candidates: Mapped[list[dict] | None] = mapped_column(JSONBCompat, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
